#!/bin/bash

asciidoc -a linkcss -s README.adoc

cd basic
asciidoc -a linkcss -s README.adoc

cd ../hypermedia
asciidoc -a linkcss -s README.adoc

cd ../conditional
asciidoc -a linkcss -s README.adoc

cd ../events
asciidoc -a linkcss -s README.adoc

cd ../security
asciidoc -a linkcss -s README.adoc
